#! /bin/sh

# Change the cwd to the directory where this script is
cd $(dirname $0) && \

# Use fcwd to change cwd to the cwd of the focused xwindow's child process
# Use home as a fallback if the previous cd commands fail
cd $(./fcwd) || cd $HOME

# Start a file manager
pcmanfm
